/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongressesRouteImport } from './routes/congresses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as CongressesCongressIdRouteImport } from './routes/congresses.$congressId'
import { Route as ApiPublicHooksTweetIngestRouteImport } from './routes/api/public/hooks/tweet-ingest'
import { Route as ApiPublicHooksSummarizeJobRouteImport } from './routes/api/public/hooks/summarize-job'

const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressesRoute = CongressesRouteImport.update({
  id: '/congresses',
  path: '/congresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressesCongressIdRoute = CongressesCongressIdRouteImport.update({
  id: '/$congressId',
  path: '/$congressId',
  getParentRoute: () => CongressesRoute,
} as any)
const ApiPublicHooksTweetIngestRoute =
  ApiPublicHooksTweetIngestRouteImport.update({
    id: '/api/public/hooks/tweet-ingest',
    path: '/api/public/hooks/tweet-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSummarizeJobRoute =
  ApiPublicHooksSummarizeJobRouteImport.update({
    id: '/api/public/hooks/summarize-job',
    path: '/api/public/hooks/summarize-job',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/feed'
    | '/settings'
    | '/sources'
    | '/summaries'
    | '/congresses/$congressId'
    | '/sessions/$sessionId'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/tweet-ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/feed'
    | '/settings'
    | '/sources'
    | '/summaries'
    | '/congresses/$congressId'
    | '/sessions/$sessionId'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/tweet-ingest'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/feed'
    | '/settings'
    | '/sources'
    | '/summaries'
    | '/congresses/$congressId'
    | '/sessions/$sessionId'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/tweet-ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  CongressesRoute: typeof CongressesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  SummariesRoute: typeof SummariesRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  ApiPublicHooksSummarizeJobRoute: typeof ApiPublicHooksSummarizeJobRoute
  ApiPublicHooksTweetIngestRoute: typeof ApiPublicHooksTweetIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresses': {
      id: '/congresses'
      path: '/congresses'
      fullPath: '/congresses'
      preLoaderRoute: typeof CongressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresses/$congressId': {
      id: '/congresses/$congressId'
      path: '/$congressId'
      fullPath: '/congresses/$congressId'
      preLoaderRoute: typeof CongressesCongressIdRouteImport
      parentRoute: typeof CongressesRoute
    }
    '/api/public/hooks/tweet-ingest': {
      id: '/api/public/hooks/tweet-ingest'
      path: '/api/public/hooks/tweet-ingest'
      fullPath: '/api/public/hooks/tweet-ingest'
      preLoaderRoute: typeof ApiPublicHooksTweetIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/summarize-job': {
      id: '/api/public/hooks/summarize-job'
      path: '/api/public/hooks/summarize-job'
      fullPath: '/api/public/hooks/summarize-job'
      preLoaderRoute: typeof ApiPublicHooksSummarizeJobRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CongressesRouteChildren {
  CongressesCongressIdRoute: typeof CongressesCongressIdRoute
}

const CongressesRouteChildren: CongressesRouteChildren = {
  CongressesCongressIdRoute: CongressesCongressIdRoute,
}

const CongressesRouteWithChildren = CongressesRoute._addFileChildren(
  CongressesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  CongressesRoute: CongressesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  SummariesRoute: SummariesRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  ApiPublicHooksSummarizeJobRoute: ApiPublicHooksSummarizeJobRoute,
  ApiPublicHooksTweetIngestRoute: ApiPublicHooksTweetIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
