/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongressesRouteImport } from './routes/congresses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SummariesDigestsRouteImport } from './routes/summaries.digests'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CongressesCongressIdRouteImport } from './routes/congresses.$congressId'
import { Route as ApiSuggestCongressRouteImport } from './routes/api/suggest-congress'
import { Route as ApiLookupHandleRouteImport } from './routes/api/lookup-handle'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminIngestionRouteImport } from './routes/admin.ingestion'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksTweetIngestRouteImport } from './routes/api/public/hooks/tweet-ingest'
import { Route as ApiPublicHooksTestHierarchyParseRouteImport } from './routes/api/public/hooks/test-hierarchy-parse'
import { Route as ApiPublicHooksSummarizeJobRouteImport } from './routes/api/public/hooks/summarize-job'
import { Route as ApiPublicHooksSendDigestsRouteImport } from './routes/api/public/hooks/send-digests'
import { Route as ApiPublicHooksProcessIngestQueueRouteImport } from './routes/api/public/hooks/process-ingest-queue'
import { Route as ApiPublicHooksMatchTweetsToSessionsRouteImport } from './routes/api/public/hooks/match-tweets-to-sessions'
import { Route as ApiPublicHooksBackfillHierarchyRecentRouteImport } from './routes/api/public/hooks/backfill-hierarchy-recent'
import { Route as ApiPublicHooksAggregateSourceCandidatesRouteImport } from './routes/api/public/hooks/aggregate-source-candidates'

const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressesRoute = CongressesRouteImport.update({
  id: '/congresses',
  path: '/congresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariesDigestsRoute = SummariesDigestsRouteImport.update({
  id: '/digests',
  path: '/digests',
  getParentRoute: () => SummariesRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressesCongressIdRoute = CongressesCongressIdRouteImport.update({
  id: '/$congressId',
  path: '/$congressId',
  getParentRoute: () => CongressesRoute,
} as any)
const ApiSuggestCongressRoute = ApiSuggestCongressRouteImport.update({
  id: '/api/suggest-congress',
  path: '/api/suggest-congress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupHandleRoute = ApiLookupHandleRouteImport.update({
  id: '/api/lookup-handle',
  path: '/api/lookup-handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/admin/recommendations',
  path: '/admin/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestionRoute = AdminIngestionRouteImport.update({
  id: '/admin/ingestion',
  path: '/admin/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTweetIngestRoute =
  ApiPublicHooksTweetIngestRouteImport.update({
    id: '/api/public/hooks/tweet-ingest',
    path: '/api/public/hooks/tweet-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTestHierarchyParseRoute =
  ApiPublicHooksTestHierarchyParseRouteImport.update({
    id: '/api/public/hooks/test-hierarchy-parse',
    path: '/api/public/hooks/test-hierarchy-parse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSummarizeJobRoute =
  ApiPublicHooksSummarizeJobRouteImport.update({
    id: '/api/public/hooks/summarize-job',
    path: '/api/public/hooks/summarize-job',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendDigestsRoute =
  ApiPublicHooksSendDigestsRouteImport.update({
    id: '/api/public/hooks/send-digests',
    path: '/api/public/hooks/send-digests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessIngestQueueRoute =
  ApiPublicHooksProcessIngestQueueRouteImport.update({
    id: '/api/public/hooks/process-ingest-queue',
    path: '/api/public/hooks/process-ingest-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMatchTweetsToSessionsRoute =
  ApiPublicHooksMatchTweetsToSessionsRouteImport.update({
    id: '/api/public/hooks/match-tweets-to-sessions',
    path: '/api/public/hooks/match-tweets-to-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillHierarchyRecentRoute =
  ApiPublicHooksBackfillHierarchyRecentRouteImport.update({
    id: '/api/public/hooks/backfill-hierarchy-recent',
    path: '/api/public/hooks/backfill-hierarchy-recent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAggregateSourceCandidatesRoute =
  ApiPublicHooksAggregateSourceCandidatesRouteImport.update({
    id: '/api/public/hooks/aggregate-source-candidates',
    path: '/api/public/hooks/aggregate-source-candidates',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRouteWithChildren
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/api/lookup-handle': typeof ApiLookupHandleRoute
  '/api/suggest-congress': typeof ApiSuggestCongressRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/summaries/digests': typeof SummariesDigestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/aggregate-source-candidates': typeof ApiPublicHooksAggregateSourceCandidatesRoute
  '/api/public/hooks/backfill-hierarchy-recent': typeof ApiPublicHooksBackfillHierarchyRecentRoute
  '/api/public/hooks/match-tweets-to-sessions': typeof ApiPublicHooksMatchTweetsToSessionsRoute
  '/api/public/hooks/process-ingest-queue': typeof ApiPublicHooksProcessIngestQueueRoute
  '/api/public/hooks/send-digests': typeof ApiPublicHooksSendDigestsRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/test-hierarchy-parse': typeof ApiPublicHooksTestHierarchyParseRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRouteWithChildren
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/api/lookup-handle': typeof ApiLookupHandleRoute
  '/api/suggest-congress': typeof ApiSuggestCongressRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/summaries/digests': typeof SummariesDigestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/aggregate-source-candidates': typeof ApiPublicHooksAggregateSourceCandidatesRoute
  '/api/public/hooks/backfill-hierarchy-recent': typeof ApiPublicHooksBackfillHierarchyRecentRoute
  '/api/public/hooks/match-tweets-to-sessions': typeof ApiPublicHooksMatchTweetsToSessionsRoute
  '/api/public/hooks/process-ingest-queue': typeof ApiPublicHooksProcessIngestQueueRoute
  '/api/public/hooks/send-digests': typeof ApiPublicHooksSendDigestsRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/test-hierarchy-parse': typeof ApiPublicHooksTestHierarchyParseRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRouteWithChildren
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/api/lookup-handle': typeof ApiLookupHandleRoute
  '/api/suggest-congress': typeof ApiSuggestCongressRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/summaries/digests': typeof SummariesDigestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/aggregate-source-candidates': typeof ApiPublicHooksAggregateSourceCandidatesRoute
  '/api/public/hooks/backfill-hierarchy-recent': typeof ApiPublicHooksBackfillHierarchyRecentRoute
  '/api/public/hooks/match-tweets-to-sessions': typeof ApiPublicHooksMatchTweetsToSessionsRoute
  '/api/public/hooks/process-ingest-queue': typeof ApiPublicHooksProcessIngestQueueRoute
  '/api/public/hooks/send-digests': typeof ApiPublicHooksSendDigestsRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/test-hierarchy-parse': typeof ApiPublicHooksTestHierarchyParseRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/settings'
    | '/sources'
    | '/summaries'
    | '/admin/ingestion'
    | '/admin/recommendations'
    | '/api/lookup-handle'
    | '/api/suggest-congress'
    | '/congresses/$congressId'
    | '/email/unsubscribe'
    | '/sessions/$sessionId'
    | '/summaries/digests'
    | '/lovable/email/suppression'
    | '/api/public/hooks/aggregate-source-candidates'
    | '/api/public/hooks/backfill-hierarchy-recent'
    | '/api/public/hooks/match-tweets-to-sessions'
    | '/api/public/hooks/process-ingest-queue'
    | '/api/public/hooks/send-digests'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/test-hierarchy-parse'
    | '/api/public/hooks/tweet-ingest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/settings'
    | '/sources'
    | '/summaries'
    | '/admin/ingestion'
    | '/admin/recommendations'
    | '/api/lookup-handle'
    | '/api/suggest-congress'
    | '/congresses/$congressId'
    | '/email/unsubscribe'
    | '/sessions/$sessionId'
    | '/summaries/digests'
    | '/lovable/email/suppression'
    | '/api/public/hooks/aggregate-source-candidates'
    | '/api/public/hooks/backfill-hierarchy-recent'
    | '/api/public/hooks/match-tweets-to-sessions'
    | '/api/public/hooks/process-ingest-queue'
    | '/api/public/hooks/send-digests'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/test-hierarchy-parse'
    | '/api/public/hooks/tweet-ingest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/settings'
    | '/sources'
    | '/summaries'
    | '/admin/ingestion'
    | '/admin/recommendations'
    | '/api/lookup-handle'
    | '/api/suggest-congress'
    | '/congresses/$congressId'
    | '/email/unsubscribe'
    | '/sessions/$sessionId'
    | '/summaries/digests'
    | '/lovable/email/suppression'
    | '/api/public/hooks/aggregate-source-candidates'
    | '/api/public/hooks/backfill-hierarchy-recent'
    | '/api/public/hooks/match-tweets-to-sessions'
    | '/api/public/hooks/process-ingest-queue'
    | '/api/public/hooks/send-digests'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/test-hierarchy-parse'
    | '/api/public/hooks/tweet-ingest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  CongressesRoute: typeof CongressesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  FeedRoute: typeof FeedRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  SummariesRoute: typeof SummariesRouteWithChildren
  AdminIngestionRoute: typeof AdminIngestionRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  ApiLookupHandleRoute: typeof ApiLookupHandleRoute
  ApiSuggestCongressRoute: typeof ApiSuggestCongressRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAggregateSourceCandidatesRoute: typeof ApiPublicHooksAggregateSourceCandidatesRoute
  ApiPublicHooksBackfillHierarchyRecentRoute: typeof ApiPublicHooksBackfillHierarchyRecentRoute
  ApiPublicHooksMatchTweetsToSessionsRoute: typeof ApiPublicHooksMatchTweetsToSessionsRoute
  ApiPublicHooksProcessIngestQueueRoute: typeof ApiPublicHooksProcessIngestQueueRoute
  ApiPublicHooksSendDigestsRoute: typeof ApiPublicHooksSendDigestsRoute
  ApiPublicHooksSummarizeJobRoute: typeof ApiPublicHooksSummarizeJobRoute
  ApiPublicHooksTestHierarchyParseRoute: typeof ApiPublicHooksTestHierarchyParseRoute
  ApiPublicHooksTweetIngestRoute: typeof ApiPublicHooksTweetIngestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresses': {
      id: '/congresses'
      path: '/congresses'
      fullPath: '/congresses'
      preLoaderRoute: typeof CongressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summaries/digests': {
      id: '/summaries/digests'
      path: '/digests'
      fullPath: '/summaries/digests'
      preLoaderRoute: typeof SummariesDigestsRouteImport
      parentRoute: typeof SummariesRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresses/$congressId': {
      id: '/congresses/$congressId'
      path: '/$congressId'
      fullPath: '/congresses/$congressId'
      preLoaderRoute: typeof CongressesCongressIdRouteImport
      parentRoute: typeof CongressesRoute
    }
    '/api/suggest-congress': {
      id: '/api/suggest-congress'
      path: '/api/suggest-congress'
      fullPath: '/api/suggest-congress'
      preLoaderRoute: typeof ApiSuggestCongressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookup-handle': {
      id: '/api/lookup-handle'
      path: '/api/lookup-handle'
      fullPath: '/api/lookup-handle'
      preLoaderRoute: typeof ApiLookupHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/admin/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingestion': {
      id: '/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tweet-ingest': {
      id: '/api/public/hooks/tweet-ingest'
      path: '/api/public/hooks/tweet-ingest'
      fullPath: '/api/public/hooks/tweet-ingest'
      preLoaderRoute: typeof ApiPublicHooksTweetIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-hierarchy-parse': {
      id: '/api/public/hooks/test-hierarchy-parse'
      path: '/api/public/hooks/test-hierarchy-parse'
      fullPath: '/api/public/hooks/test-hierarchy-parse'
      preLoaderRoute: typeof ApiPublicHooksTestHierarchyParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/summarize-job': {
      id: '/api/public/hooks/summarize-job'
      path: '/api/public/hooks/summarize-job'
      fullPath: '/api/public/hooks/summarize-job'
      preLoaderRoute: typeof ApiPublicHooksSummarizeJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-digests': {
      id: '/api/public/hooks/send-digests'
      path: '/api/public/hooks/send-digests'
      fullPath: '/api/public/hooks/send-digests'
      preLoaderRoute: typeof ApiPublicHooksSendDigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-ingest-queue': {
      id: '/api/public/hooks/process-ingest-queue'
      path: '/api/public/hooks/process-ingest-queue'
      fullPath: '/api/public/hooks/process-ingest-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessIngestQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/match-tweets-to-sessions': {
      id: '/api/public/hooks/match-tweets-to-sessions'
      path: '/api/public/hooks/match-tweets-to-sessions'
      fullPath: '/api/public/hooks/match-tweets-to-sessions'
      preLoaderRoute: typeof ApiPublicHooksMatchTweetsToSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-hierarchy-recent': {
      id: '/api/public/hooks/backfill-hierarchy-recent'
      path: '/api/public/hooks/backfill-hierarchy-recent'
      fullPath: '/api/public/hooks/backfill-hierarchy-recent'
      preLoaderRoute: typeof ApiPublicHooksBackfillHierarchyRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/aggregate-source-candidates': {
      id: '/api/public/hooks/aggregate-source-candidates'
      path: '/api/public/hooks/aggregate-source-candidates'
      fullPath: '/api/public/hooks/aggregate-source-candidates'
      preLoaderRoute: typeof ApiPublicHooksAggregateSourceCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CongressesRouteChildren {
  CongressesCongressIdRoute: typeof CongressesCongressIdRoute
}

const CongressesRouteChildren: CongressesRouteChildren = {
  CongressesCongressIdRoute: CongressesCongressIdRoute,
}

const CongressesRouteWithChildren = CongressesRoute._addFileChildren(
  CongressesRouteChildren,
)

interface SummariesRouteChildren {
  SummariesDigestsRoute: typeof SummariesDigestsRoute
}

const SummariesRouteChildren: SummariesRouteChildren = {
  SummariesDigestsRoute: SummariesDigestsRoute,
}

const SummariesRouteWithChildren = SummariesRoute._addFileChildren(
  SummariesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  CongressesRoute: CongressesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  FeedRoute: FeedRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  SummariesRoute: SummariesRouteWithChildren,
  AdminIngestionRoute: AdminIngestionRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  ApiLookupHandleRoute: ApiLookupHandleRoute,
  ApiSuggestCongressRoute: ApiSuggestCongressRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAggregateSourceCandidatesRoute:
    ApiPublicHooksAggregateSourceCandidatesRoute,
  ApiPublicHooksBackfillHierarchyRecentRoute:
    ApiPublicHooksBackfillHierarchyRecentRoute,
  ApiPublicHooksMatchTweetsToSessionsRoute:
    ApiPublicHooksMatchTweetsToSessionsRoute,
  ApiPublicHooksProcessIngestQueueRoute: ApiPublicHooksProcessIngestQueueRoute,
  ApiPublicHooksSendDigestsRoute: ApiPublicHooksSendDigestsRoute,
  ApiPublicHooksSummarizeJobRoute: ApiPublicHooksSummarizeJobRoute,
  ApiPublicHooksTestHierarchyParseRoute: ApiPublicHooksTestHierarchyParseRoute,
  ApiPublicHooksTweetIngestRoute: ApiPublicHooksTweetIngestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
