/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeRouteImport } from './routes/me'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DigestsRouteImport } from './routes/digests'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongressesRouteImport } from './routes/congresses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesHandleRouteImport } from './routes/sources_.$handle'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as MeXAccountRouteImport } from './routes/me.x-account'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as MePreferencesRouteImport } from './routes/me.preferences'
import { Route as MePostsRouteImport } from './routes/me.posts'
import { Route as MeNotificationsRouteImport } from './routes/me.notifications'
import { Route as MeFollowingRouteImport } from './routes/me.following'
import { Route as MeAiRouteImport } from './routes/me.ai'
import { Route as HelpInstructionsRouteImport } from './routes/help.instructions'
import { Route as GroupsSlugRouteImport } from './routes/groups.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DiscoverGroupsRouteImport } from './routes/discover.groups'
import { Route as CongressesCongressIdRouteImport } from './routes/congresses.$congressId'
import { Route as ConfigurationBrainstormRouteImport } from './routes/configuration.brainstorm'
import { Route as ApiSuggestCongressRouteImport } from './routes/api/suggest-congress'
import { Route as ApiLookupHandleRouteImport } from './routes/api/lookup-handle'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as AdminIngestionRouteImport } from './routes/admin.ingestion'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminEmailDiagnosticsRouteImport } from './routes/admin.email-diagnostics'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicAccessRequestRouteImport } from './routes/api/public/access-request'
import { Route as ApiAuthPasswordRouteImport } from './routes/api/auth/password'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWatchlistMuteTokenRouteImport } from './routes/api/public/watchlist-mute.$token'
import { Route as ApiPublicHooksWatchlistFlushRouteImport } from './routes/api/public/hooks/watchlist-flush'
import { Route as ApiPublicHooksTweetIngestRouteImport } from './routes/api/public/hooks/tweet-ingest'
import { Route as ApiPublicHooksTestHierarchyParseRouteImport } from './routes/api/public/hooks/test-hierarchy-parse'
import { Route as ApiPublicHooksSummarizeJobRouteImport } from './routes/api/public/hooks/summarize-job'
import { Route as ApiPublicHooksSendDigestsRouteImport } from './routes/api/public/hooks/send-digests'
import { Route as ApiPublicHooksResetDemoAccountRouteImport } from './routes/api/public/hooks/reset-demo-account'
import { Route as ApiPublicHooksProcessIngestQueueRouteImport } from './routes/api/public/hooks/process-ingest-queue'
import { Route as ApiPublicHooksNominateGroupMembersRouteImport } from './routes/api/public/hooks/nominate-group-members'
import { Route as ApiPublicHooksMatchTweetsToSessionsRouteImport } from './routes/api/public/hooks/match-tweets-to-sessions'
import { Route as ApiPublicHooksCheckQueueHealthRouteImport } from './routes/api/public/hooks/check-queue-health'
import { Route as ApiPublicHooksBackfillHierarchyRecentRouteImport } from './routes/api/public/hooks/backfill-hierarchy-recent'
import { Route as ApiPublicHooksAggregateSourceCandidatesRouteImport } from './routes/api/public/hooks/aggregate-source-candidates'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestsRoute = DigestsRouteImport.update({
  id: '/digests',
  path: '/digests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressesRoute = CongressesRouteImport.update({
  id: '/congresses',
  path: '/congresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesHandleRoute = SourcesHandleRouteImport.update({
  id: '/sources_/$handle',
  path: '/sources/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeXAccountRoute = MeXAccountRouteImport.update({
  id: '/x-account',
  path: '/x-account',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MeRoute,
} as any)
const MePreferencesRoute = MePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => MeRoute,
} as any)
const MePostsRoute = MePostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => MeRoute,
} as any)
const MeNotificationsRoute = MeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MeRoute,
} as any)
const MeFollowingRoute = MeFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => MeRoute,
} as any)
const MeAiRoute = MeAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => MeRoute,
} as any)
const HelpInstructionsRoute = HelpInstructionsRouteImport.update({
  id: '/help/instructions',
  path: '/help/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverGroupsRoute = DiscoverGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DiscoverRoute,
} as any)
const CongressesCongressIdRoute = CongressesCongressIdRouteImport.update({
  id: '/$congressId',
  path: '/$congressId',
  getParentRoute: () => CongressesRoute,
} as any)
const ConfigurationBrainstormRoute = ConfigurationBrainstormRouteImport.update({
  id: '/configuration/brainstorm',
  path: '/configuration/brainstorm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestCongressRoute = ApiSuggestCongressRouteImport.update({
  id: '/api/suggest-congress',
  path: '/api/suggest-congress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupHandleRoute = ApiLookupHandleRouteImport.update({
  id: '/api/lookup-handle',
  path: '/api/lookup-handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/admin/recommendations',
  path: '/admin/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/admin/ops',
  path: '/admin/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestionRoute = AdminIngestionRouteImport.update({
  id: '/admin/ingestion',
  path: '/admin/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailDiagnosticsRoute = AdminEmailDiagnosticsRouteImport.update({
  id: '/admin/email-diagnostics',
  path: '/admin/email-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccessRequestRoute = ApiPublicAccessRequestRouteImport.update({
  id: '/api/public/access-request',
  path: '/api/public/access-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/api/auth/password',
  path: '/api/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWatchlistMuteTokenRoute =
  ApiPublicWatchlistMuteTokenRouteImport.update({
    id: '/api/public/watchlist-mute/$token',
    path: '/api/public/watchlist-mute/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWatchlistFlushRoute =
  ApiPublicHooksWatchlistFlushRouteImport.update({
    id: '/api/public/hooks/watchlist-flush',
    path: '/api/public/hooks/watchlist-flush',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTweetIngestRoute =
  ApiPublicHooksTweetIngestRouteImport.update({
    id: '/api/public/hooks/tweet-ingest',
    path: '/api/public/hooks/tweet-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTestHierarchyParseRoute =
  ApiPublicHooksTestHierarchyParseRouteImport.update({
    id: '/api/public/hooks/test-hierarchy-parse',
    path: '/api/public/hooks/test-hierarchy-parse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSummarizeJobRoute =
  ApiPublicHooksSummarizeJobRouteImport.update({
    id: '/api/public/hooks/summarize-job',
    path: '/api/public/hooks/summarize-job',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendDigestsRoute =
  ApiPublicHooksSendDigestsRouteImport.update({
    id: '/api/public/hooks/send-digests',
    path: '/api/public/hooks/send-digests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResetDemoAccountRoute =
  ApiPublicHooksResetDemoAccountRouteImport.update({
    id: '/api/public/hooks/reset-demo-account',
    path: '/api/public/hooks/reset-demo-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessIngestQueueRoute =
  ApiPublicHooksProcessIngestQueueRouteImport.update({
    id: '/api/public/hooks/process-ingest-queue',
    path: '/api/public/hooks/process-ingest-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNominateGroupMembersRoute =
  ApiPublicHooksNominateGroupMembersRouteImport.update({
    id: '/api/public/hooks/nominate-group-members',
    path: '/api/public/hooks/nominate-group-members',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMatchTweetsToSessionsRoute =
  ApiPublicHooksMatchTweetsToSessionsRouteImport.update({
    id: '/api/public/hooks/match-tweets-to-sessions',
    path: '/api/public/hooks/match-tweets-to-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckQueueHealthRoute =
  ApiPublicHooksCheckQueueHealthRouteImport.update({
    id: '/api/public/hooks/check-queue-health',
    path: '/api/public/hooks/check-queue-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillHierarchyRecentRoute =
  ApiPublicHooksBackfillHierarchyRecentRouteImport.update({
    id: '/api/public/hooks/backfill-hierarchy-recent',
    path: '/api/public/hooks/backfill-hierarchy-recent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAggregateSourceCandidatesRoute =
  ApiPublicHooksAggregateSourceCandidatesRouteImport.update({
    id: '/api/public/hooks/aggregate-source-candidates',
    path: '/api/public/hooks/aggregate-source-candidates',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digests': typeof DigestsRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/feed': typeof FeedRoute
  '/me': typeof MeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/email-diagnostics': typeof AdminEmailDiagnosticsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/lookup-handle': typeof ApiLookupHandleRoute
  '/api/suggest-congress': typeof ApiSuggestCongressRoute
  '/configuration/brainstorm': typeof ConfigurationBrainstormRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/discover/groups': typeof DiscoverGroupsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/help/instructions': typeof HelpInstructionsRoute
  '/me/ai': typeof MeAiRoute
  '/me/following': typeof MeFollowingRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/posts': typeof MePostsRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/profile': typeof MeProfileRoute
  '/me/x-account': typeof MeXAccountRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sources/$handle': typeof SourcesHandleRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/public/access-request': typeof ApiPublicAccessRequestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/aggregate-source-candidates': typeof ApiPublicHooksAggregateSourceCandidatesRoute
  '/api/public/hooks/backfill-hierarchy-recent': typeof ApiPublicHooksBackfillHierarchyRecentRoute
  '/api/public/hooks/check-queue-health': typeof ApiPublicHooksCheckQueueHealthRoute
  '/api/public/hooks/match-tweets-to-sessions': typeof ApiPublicHooksMatchTweetsToSessionsRoute
  '/api/public/hooks/nominate-group-members': typeof ApiPublicHooksNominateGroupMembersRoute
  '/api/public/hooks/process-ingest-queue': typeof ApiPublicHooksProcessIngestQueueRoute
  '/api/public/hooks/reset-demo-account': typeof ApiPublicHooksResetDemoAccountRoute
  '/api/public/hooks/send-digests': typeof ApiPublicHooksSendDigestsRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/test-hierarchy-parse': typeof ApiPublicHooksTestHierarchyParseRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
  '/api/public/hooks/watchlist-flush': typeof ApiPublicHooksWatchlistFlushRoute
  '/api/public/watchlist-mute/$token': typeof ApiPublicWatchlistMuteTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digests': typeof DigestsRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/feed': typeof FeedRoute
  '/me': typeof MeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/email-diagnostics': typeof AdminEmailDiagnosticsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/lookup-handle': typeof ApiLookupHandleRoute
  '/api/suggest-congress': typeof ApiSuggestCongressRoute
  '/configuration/brainstorm': typeof ConfigurationBrainstormRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/discover/groups': typeof DiscoverGroupsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/help/instructions': typeof HelpInstructionsRoute
  '/me/ai': typeof MeAiRoute
  '/me/following': typeof MeFollowingRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/posts': typeof MePostsRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/profile': typeof MeProfileRoute
  '/me/x-account': typeof MeXAccountRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sources/$handle': typeof SourcesHandleRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/public/access-request': typeof ApiPublicAccessRequestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/aggregate-source-candidates': typeof ApiPublicHooksAggregateSourceCandidatesRoute
  '/api/public/hooks/backfill-hierarchy-recent': typeof ApiPublicHooksBackfillHierarchyRecentRoute
  '/api/public/hooks/check-queue-health': typeof ApiPublicHooksCheckQueueHealthRoute
  '/api/public/hooks/match-tweets-to-sessions': typeof ApiPublicHooksMatchTweetsToSessionsRoute
  '/api/public/hooks/nominate-group-members': typeof ApiPublicHooksNominateGroupMembersRoute
  '/api/public/hooks/process-ingest-queue': typeof ApiPublicHooksProcessIngestQueueRoute
  '/api/public/hooks/reset-demo-account': typeof ApiPublicHooksResetDemoAccountRoute
  '/api/public/hooks/send-digests': typeof ApiPublicHooksSendDigestsRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/test-hierarchy-parse': typeof ApiPublicHooksTestHierarchyParseRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
  '/api/public/hooks/watchlist-flush': typeof ApiPublicHooksWatchlistFlushRoute
  '/api/public/watchlist-mute/$token': typeof ApiPublicWatchlistMuteTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/congresses': typeof CongressesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/digests': typeof DigestsRoute
  '/discover': typeof DiscoverRouteWithChildren
  '/feed': typeof FeedRoute
  '/me': typeof MeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/summaries': typeof SummariesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/email-diagnostics': typeof AdminEmailDiagnosticsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/lookup-handle': typeof ApiLookupHandleRoute
  '/api/suggest-congress': typeof ApiSuggestCongressRoute
  '/configuration/brainstorm': typeof ConfigurationBrainstormRoute
  '/congresses/$congressId': typeof CongressesCongressIdRoute
  '/discover/groups': typeof DiscoverGroupsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/help/instructions': typeof HelpInstructionsRoute
  '/me/ai': typeof MeAiRoute
  '/me/following': typeof MeFollowingRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/posts': typeof MePostsRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/profile': typeof MeProfileRoute
  '/me/x-account': typeof MeXAccountRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sources_/$handle': typeof SourcesHandleRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/public/access-request': typeof ApiPublicAccessRequestRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/aggregate-source-candidates': typeof ApiPublicHooksAggregateSourceCandidatesRoute
  '/api/public/hooks/backfill-hierarchy-recent': typeof ApiPublicHooksBackfillHierarchyRecentRoute
  '/api/public/hooks/check-queue-health': typeof ApiPublicHooksCheckQueueHealthRoute
  '/api/public/hooks/match-tweets-to-sessions': typeof ApiPublicHooksMatchTweetsToSessionsRoute
  '/api/public/hooks/nominate-group-members': typeof ApiPublicHooksNominateGroupMembersRoute
  '/api/public/hooks/process-ingest-queue': typeof ApiPublicHooksProcessIngestQueueRoute
  '/api/public/hooks/reset-demo-account': typeof ApiPublicHooksResetDemoAccountRoute
  '/api/public/hooks/send-digests': typeof ApiPublicHooksSendDigestsRoute
  '/api/public/hooks/summarize-job': typeof ApiPublicHooksSummarizeJobRoute
  '/api/public/hooks/test-hierarchy-parse': typeof ApiPublicHooksTestHierarchyParseRoute
  '/api/public/hooks/tweet-ingest': typeof ApiPublicHooksTweetIngestRoute
  '/api/public/hooks/watchlist-flush': typeof ApiPublicHooksWatchlistFlushRoute
  '/api/public/watchlist-mute/$token': typeof ApiPublicWatchlistMuteTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/alerts'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/digests'
    | '/discover'
    | '/feed'
    | '/me'
    | '/settings'
    | '/sitemap.xml'
    | '/sources'
    | '/summaries'
    | '/unsubscribe'
    | '/admin/email-diagnostics'
    | '/admin/groups'
    | '/admin/ingestion'
    | '/admin/ops'
    | '/admin/recommendations'
    | '/admin/users'
    | '/api/lookup-handle'
    | '/api/suggest-congress'
    | '/configuration/brainstorm'
    | '/congresses/$congressId'
    | '/discover/groups'
    | '/email/unsubscribe'
    | '/groups/$slug'
    | '/help/instructions'
    | '/me/ai'
    | '/me/following'
    | '/me/notifications'
    | '/me/posts'
    | '/me/preferences'
    | '/me/profile'
    | '/me/x-account'
    | '/sessions/$sessionId'
    | '/sources/$handle'
    | '/api/auth/password'
    | '/api/public/access-request'
    | '/lovable/email/suppression'
    | '/api/public/hooks/aggregate-source-candidates'
    | '/api/public/hooks/backfill-hierarchy-recent'
    | '/api/public/hooks/check-queue-health'
    | '/api/public/hooks/match-tweets-to-sessions'
    | '/api/public/hooks/nominate-group-members'
    | '/api/public/hooks/process-ingest-queue'
    | '/api/public/hooks/reset-demo-account'
    | '/api/public/hooks/send-digests'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/test-hierarchy-parse'
    | '/api/public/hooks/tweet-ingest'
    | '/api/public/hooks/watchlist-flush'
    | '/api/public/watchlist-mute/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/alerts'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/digests'
    | '/discover'
    | '/feed'
    | '/me'
    | '/settings'
    | '/sitemap.xml'
    | '/sources'
    | '/summaries'
    | '/unsubscribe'
    | '/admin/email-diagnostics'
    | '/admin/groups'
    | '/admin/ingestion'
    | '/admin/ops'
    | '/admin/recommendations'
    | '/admin/users'
    | '/api/lookup-handle'
    | '/api/suggest-congress'
    | '/configuration/brainstorm'
    | '/congresses/$congressId'
    | '/discover/groups'
    | '/email/unsubscribe'
    | '/groups/$slug'
    | '/help/instructions'
    | '/me/ai'
    | '/me/following'
    | '/me/notifications'
    | '/me/posts'
    | '/me/preferences'
    | '/me/profile'
    | '/me/x-account'
    | '/sessions/$sessionId'
    | '/sources/$handle'
    | '/api/auth/password'
    | '/api/public/access-request'
    | '/lovable/email/suppression'
    | '/api/public/hooks/aggregate-source-candidates'
    | '/api/public/hooks/backfill-hierarchy-recent'
    | '/api/public/hooks/check-queue-health'
    | '/api/public/hooks/match-tweets-to-sessions'
    | '/api/public/hooks/nominate-group-members'
    | '/api/public/hooks/process-ingest-queue'
    | '/api/public/hooks/reset-demo-account'
    | '/api/public/hooks/send-digests'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/test-hierarchy-parse'
    | '/api/public/hooks/tweet-ingest'
    | '/api/public/hooks/watchlist-flush'
    | '/api/public/watchlist-mute/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/alerts'
    | '/auth'
    | '/congresses'
    | '/dashboard'
    | '/digests'
    | '/discover'
    | '/feed'
    | '/me'
    | '/settings'
    | '/sitemap.xml'
    | '/sources'
    | '/summaries'
    | '/unsubscribe'
    | '/admin/email-diagnostics'
    | '/admin/groups'
    | '/admin/ingestion'
    | '/admin/ops'
    | '/admin/recommendations'
    | '/admin/users'
    | '/api/lookup-handle'
    | '/api/suggest-congress'
    | '/configuration/brainstorm'
    | '/congresses/$congressId'
    | '/discover/groups'
    | '/email/unsubscribe'
    | '/groups/$slug'
    | '/help/instructions'
    | '/me/ai'
    | '/me/following'
    | '/me/notifications'
    | '/me/posts'
    | '/me/preferences'
    | '/me/profile'
    | '/me/x-account'
    | '/sessions/$sessionId'
    | '/sources_/$handle'
    | '/api/auth/password'
    | '/api/public/access-request'
    | '/lovable/email/suppression'
    | '/api/public/hooks/aggregate-source-candidates'
    | '/api/public/hooks/backfill-hierarchy-recent'
    | '/api/public/hooks/check-queue-health'
    | '/api/public/hooks/match-tweets-to-sessions'
    | '/api/public/hooks/nominate-group-members'
    | '/api/public/hooks/process-ingest-queue'
    | '/api/public/hooks/reset-demo-account'
    | '/api/public/hooks/send-digests'
    | '/api/public/hooks/summarize-job'
    | '/api/public/hooks/test-hierarchy-parse'
    | '/api/public/hooks/tweet-ingest'
    | '/api/public/hooks/watchlist-flush'
    | '/api/public/watchlist-mute/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  CongressesRoute: typeof CongressesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DigestsRoute: typeof DigestsRoute
  DiscoverRoute: typeof DiscoverRouteWithChildren
  FeedRoute: typeof FeedRoute
  MeRoute: typeof MeRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  SummariesRoute: typeof SummariesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminEmailDiagnosticsRoute: typeof AdminEmailDiagnosticsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminIngestionRoute: typeof AdminIngestionRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiLookupHandleRoute: typeof ApiLookupHandleRoute
  ApiSuggestCongressRoute: typeof ApiSuggestCongressRoute
  ConfigurationBrainstormRoute: typeof ConfigurationBrainstormRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GroupsSlugRoute: typeof GroupsSlugRoute
  HelpInstructionsRoute: typeof HelpInstructionsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SourcesHandleRoute: typeof SourcesHandleRoute
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
  ApiPublicAccessRequestRoute: typeof ApiPublicAccessRequestRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAggregateSourceCandidatesRoute: typeof ApiPublicHooksAggregateSourceCandidatesRoute
  ApiPublicHooksBackfillHierarchyRecentRoute: typeof ApiPublicHooksBackfillHierarchyRecentRoute
  ApiPublicHooksCheckQueueHealthRoute: typeof ApiPublicHooksCheckQueueHealthRoute
  ApiPublicHooksMatchTweetsToSessionsRoute: typeof ApiPublicHooksMatchTweetsToSessionsRoute
  ApiPublicHooksNominateGroupMembersRoute: typeof ApiPublicHooksNominateGroupMembersRoute
  ApiPublicHooksProcessIngestQueueRoute: typeof ApiPublicHooksProcessIngestQueueRoute
  ApiPublicHooksResetDemoAccountRoute: typeof ApiPublicHooksResetDemoAccountRoute
  ApiPublicHooksSendDigestsRoute: typeof ApiPublicHooksSendDigestsRoute
  ApiPublicHooksSummarizeJobRoute: typeof ApiPublicHooksSummarizeJobRoute
  ApiPublicHooksTestHierarchyParseRoute: typeof ApiPublicHooksTestHierarchyParseRoute
  ApiPublicHooksTweetIngestRoute: typeof ApiPublicHooksTweetIngestRoute
  ApiPublicHooksWatchlistFlushRoute: typeof ApiPublicHooksWatchlistFlushRoute
  ApiPublicWatchlistMuteTokenRoute: typeof ApiPublicWatchlistMuteTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digests': {
      id: '/digests'
      path: '/digests'
      fullPath: '/digests'
      preLoaderRoute: typeof DigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresses': {
      id: '/congresses'
      path: '/congresses'
      fullPath: '/congresses'
      preLoaderRoute: typeof CongressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources_/$handle': {
      id: '/sources_/$handle'
      path: '/sources/$handle'
      fullPath: '/sources/$handle'
      preLoaderRoute: typeof SourcesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/x-account': {
      id: '/me/x-account'
      path: '/x-account'
      fullPath: '/me/x-account'
      preLoaderRoute: typeof MeXAccountRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/preferences': {
      id: '/me/preferences'
      path: '/preferences'
      fullPath: '/me/preferences'
      preLoaderRoute: typeof MePreferencesRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/posts': {
      id: '/me/posts'
      path: '/posts'
      fullPath: '/me/posts'
      preLoaderRoute: typeof MePostsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/notifications': {
      id: '/me/notifications'
      path: '/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof MeNotificationsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/following': {
      id: '/me/following'
      path: '/following'
      fullPath: '/me/following'
      preLoaderRoute: typeof MeFollowingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/ai': {
      id: '/me/ai'
      path: '/ai'
      fullPath: '/me/ai'
      preLoaderRoute: typeof MeAiRouteImport
      parentRoute: typeof MeRoute
    }
    '/help/instructions': {
      id: '/help/instructions'
      path: '/help/instructions'
      fullPath: '/help/instructions'
      preLoaderRoute: typeof HelpInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/groups': {
      id: '/discover/groups'
      path: '/groups'
      fullPath: '/discover/groups'
      preLoaderRoute: typeof DiscoverGroupsRouteImport
      parentRoute: typeof DiscoverRoute
    }
    '/congresses/$congressId': {
      id: '/congresses/$congressId'
      path: '/$congressId'
      fullPath: '/congresses/$congressId'
      preLoaderRoute: typeof CongressesCongressIdRouteImport
      parentRoute: typeof CongressesRoute
    }
    '/configuration/brainstorm': {
      id: '/configuration/brainstorm'
      path: '/configuration/brainstorm'
      fullPath: '/configuration/brainstorm'
      preLoaderRoute: typeof ConfigurationBrainstormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-congress': {
      id: '/api/suggest-congress'
      path: '/api/suggest-congress'
      fullPath: '/api/suggest-congress'
      preLoaderRoute: typeof ApiSuggestCongressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookup-handle': {
      id: '/api/lookup-handle'
      path: '/api/lookup-handle'
      fullPath: '/api/lookup-handle'
      preLoaderRoute: typeof ApiLookupHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/admin/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/admin/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingestion': {
      id: '/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-diagnostics': {
      id: '/admin/email-diagnostics'
      path: '/admin/email-diagnostics'
      fullPath: '/admin/email-diagnostics'
      preLoaderRoute: typeof AdminEmailDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/access-request': {
      id: '/api/public/access-request'
      path: '/api/public/access-request'
      fullPath: '/api/public/access-request'
      preLoaderRoute: typeof ApiPublicAccessRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/api/auth/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/watchlist-mute/$token': {
      id: '/api/public/watchlist-mute/$token'
      path: '/api/public/watchlist-mute/$token'
      fullPath: '/api/public/watchlist-mute/$token'
      preLoaderRoute: typeof ApiPublicWatchlistMuteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/watchlist-flush': {
      id: '/api/public/hooks/watchlist-flush'
      path: '/api/public/hooks/watchlist-flush'
      fullPath: '/api/public/hooks/watchlist-flush'
      preLoaderRoute: typeof ApiPublicHooksWatchlistFlushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tweet-ingest': {
      id: '/api/public/hooks/tweet-ingest'
      path: '/api/public/hooks/tweet-ingest'
      fullPath: '/api/public/hooks/tweet-ingest'
      preLoaderRoute: typeof ApiPublicHooksTweetIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-hierarchy-parse': {
      id: '/api/public/hooks/test-hierarchy-parse'
      path: '/api/public/hooks/test-hierarchy-parse'
      fullPath: '/api/public/hooks/test-hierarchy-parse'
      preLoaderRoute: typeof ApiPublicHooksTestHierarchyParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/summarize-job': {
      id: '/api/public/hooks/summarize-job'
      path: '/api/public/hooks/summarize-job'
      fullPath: '/api/public/hooks/summarize-job'
      preLoaderRoute: typeof ApiPublicHooksSummarizeJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-digests': {
      id: '/api/public/hooks/send-digests'
      path: '/api/public/hooks/send-digests'
      fullPath: '/api/public/hooks/send-digests'
      preLoaderRoute: typeof ApiPublicHooksSendDigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reset-demo-account': {
      id: '/api/public/hooks/reset-demo-account'
      path: '/api/public/hooks/reset-demo-account'
      fullPath: '/api/public/hooks/reset-demo-account'
      preLoaderRoute: typeof ApiPublicHooksResetDemoAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-ingest-queue': {
      id: '/api/public/hooks/process-ingest-queue'
      path: '/api/public/hooks/process-ingest-queue'
      fullPath: '/api/public/hooks/process-ingest-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessIngestQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nominate-group-members': {
      id: '/api/public/hooks/nominate-group-members'
      path: '/api/public/hooks/nominate-group-members'
      fullPath: '/api/public/hooks/nominate-group-members'
      preLoaderRoute: typeof ApiPublicHooksNominateGroupMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/match-tweets-to-sessions': {
      id: '/api/public/hooks/match-tweets-to-sessions'
      path: '/api/public/hooks/match-tweets-to-sessions'
      fullPath: '/api/public/hooks/match-tweets-to-sessions'
      preLoaderRoute: typeof ApiPublicHooksMatchTweetsToSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-queue-health': {
      id: '/api/public/hooks/check-queue-health'
      path: '/api/public/hooks/check-queue-health'
      fullPath: '/api/public/hooks/check-queue-health'
      preLoaderRoute: typeof ApiPublicHooksCheckQueueHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-hierarchy-recent': {
      id: '/api/public/hooks/backfill-hierarchy-recent'
      path: '/api/public/hooks/backfill-hierarchy-recent'
      fullPath: '/api/public/hooks/backfill-hierarchy-recent'
      preLoaderRoute: typeof ApiPublicHooksBackfillHierarchyRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/aggregate-source-candidates': {
      id: '/api/public/hooks/aggregate-source-candidates'
      path: '/api/public/hooks/aggregate-source-candidates'
      fullPath: '/api/public/hooks/aggregate-source-candidates'
      preLoaderRoute: typeof ApiPublicHooksAggregateSourceCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CongressesRouteChildren {
  CongressesCongressIdRoute: typeof CongressesCongressIdRoute
}

const CongressesRouteChildren: CongressesRouteChildren = {
  CongressesCongressIdRoute: CongressesCongressIdRoute,
}

const CongressesRouteWithChildren = CongressesRoute._addFileChildren(
  CongressesRouteChildren,
)

interface DiscoverRouteChildren {
  DiscoverGroupsRoute: typeof DiscoverGroupsRoute
}

const DiscoverRouteChildren: DiscoverRouteChildren = {
  DiscoverGroupsRoute: DiscoverGroupsRoute,
}

const DiscoverRouteWithChildren = DiscoverRoute._addFileChildren(
  DiscoverRouteChildren,
)

interface MeRouteChildren {
  MeAiRoute: typeof MeAiRoute
  MeFollowingRoute: typeof MeFollowingRoute
  MeNotificationsRoute: typeof MeNotificationsRoute
  MePostsRoute: typeof MePostsRoute
  MePreferencesRoute: typeof MePreferencesRoute
  MeProfileRoute: typeof MeProfileRoute
  MeXAccountRoute: typeof MeXAccountRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeAiRoute: MeAiRoute,
  MeFollowingRoute: MeFollowingRoute,
  MeNotificationsRoute: MeNotificationsRoute,
  MePostsRoute: MePostsRoute,
  MePreferencesRoute: MePreferencesRoute,
  MeProfileRoute: MeProfileRoute,
  MeXAccountRoute: MeXAccountRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  CongressesRoute: CongressesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DigestsRoute: DigestsRoute,
  DiscoverRoute: DiscoverRouteWithChildren,
  FeedRoute: FeedRoute,
  MeRoute: MeRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  SummariesRoute: SummariesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminEmailDiagnosticsRoute: AdminEmailDiagnosticsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminIngestionRoute: AdminIngestionRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiLookupHandleRoute: ApiLookupHandleRoute,
  ApiSuggestCongressRoute: ApiSuggestCongressRoute,
  ConfigurationBrainstormRoute: ConfigurationBrainstormRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GroupsSlugRoute: GroupsSlugRoute,
  HelpInstructionsRoute: HelpInstructionsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SourcesHandleRoute: SourcesHandleRoute,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
  ApiPublicAccessRequestRoute: ApiPublicAccessRequestRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAggregateSourceCandidatesRoute:
    ApiPublicHooksAggregateSourceCandidatesRoute,
  ApiPublicHooksBackfillHierarchyRecentRoute:
    ApiPublicHooksBackfillHierarchyRecentRoute,
  ApiPublicHooksCheckQueueHealthRoute: ApiPublicHooksCheckQueueHealthRoute,
  ApiPublicHooksMatchTweetsToSessionsRoute:
    ApiPublicHooksMatchTweetsToSessionsRoute,
  ApiPublicHooksNominateGroupMembersRoute:
    ApiPublicHooksNominateGroupMembersRoute,
  ApiPublicHooksProcessIngestQueueRoute: ApiPublicHooksProcessIngestQueueRoute,
  ApiPublicHooksResetDemoAccountRoute: ApiPublicHooksResetDemoAccountRoute,
  ApiPublicHooksSendDigestsRoute: ApiPublicHooksSendDigestsRoute,
  ApiPublicHooksSummarizeJobRoute: ApiPublicHooksSummarizeJobRoute,
  ApiPublicHooksTestHierarchyParseRoute: ApiPublicHooksTestHierarchyParseRoute,
  ApiPublicHooksTweetIngestRoute: ApiPublicHooksTweetIngestRoute,
  ApiPublicHooksWatchlistFlushRoute: ApiPublicHooksWatchlistFlushRoute,
  ApiPublicWatchlistMuteTokenRoute: ApiPublicWatchlistMuteTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
