import * as React from "react";
import { Loader2, Sparkles, CheckCircle2, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  useAiSettings,
  AI_MODELS,
  type AiSettings as AiSettingsT,
} from "@/hooks/useAiSettings";
import { mockAiService, openAiCompatibleService } from "@/services/aiService";
import { toast } from "sonner";

export function AiSettings() {
  const { settings, save, reset } = useAiSettings();
  const [draft, setDraft] = React.useState<AiSettingsT>(settings);
  const [testing, setTesting] = React.useState(false);
  const [result, setResult] = React.useState<{
    ok: boolean;
    text: string;
  } | null>(null);

  React.useEffect(() => setDraft(settings), [settings]);

  const dirty =
    draft.useLive !== settings.useLive || draft.model !== settings.model;

  const onTest = async () => {
    setTesting(true);
    setResult(null);
    try {
      const svc = draft.useLive ? openAiCompatibleService : mockAiService;
      const r = await svc.ping(draft.model);
      setResult({ ok: true, text: r.text });
      toast.success("AI responded", { description: r.text.slice(0, 120) });
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Unknown error";
      setResult({ ok: false, text: msg });
      toast.error("AI test failed", { description: msg });
    } finally {
      setTesting(false);
    }
  };

  return (
    <div className="max-w-2xl space-y-8">
      <header>
        <div className="flex items-center gap-2 mb-1">
          <Sparkles className="w-4 h-4 text-accent" />
          <h1 className="text-lg font-semibold tracking-tight text-text-primary">
            AI Configuration
          </h1>
        </div>
        <p className="text-[13px] text-text-muted leading-relaxed">
          Summaries are generated by an OpenAI-compatible chat completions
          endpoint. Requests are proxied server-side through an edge function so
          no API keys ever reach the browser. Lovable AI Gateway is used by
          default — no key configuration required.
        </p>
      </header>

      {/* Live vs mock */}
      <section className="border border-border rounded-[3px] bg-panel p-4 space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div>
            <Label className="text-[13px] text-text-primary">
              Use live AI
            </Label>
            <p className="text-[12px] text-text-muted mt-0.5">
              When off, summaries come from local canned mock data — fast,
              deterministic, zero cost.
            </p>
          </div>
          <Switch
            checked={draft.useLive}
            onCheckedChange={(v) => setDraft({ ...draft, useLive: v })}
          />
        </div>

        <div className="space-y-2">
          <Label className="text-[13px] text-text-primary">Model</Label>
          <Select
            value={draft.model}
            onValueChange={(v) => setDraft({ ...draft, model: v })}
          >
            <SelectTrigger className="w-full">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {AI_MODELS.map((m) => (
                <SelectItem key={m.value} value={m.value}>
                  <span className="flex items-center gap-2">
                    <span className="font-mono text-[12px]">{m.value}</span>
                    {m.note && (
                      <span className="text-[10px] uppercase tracking-wider text-text-muted">
                        {m.note}
                      </span>
                    )}
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <p className="text-[11px] text-text-muted font-mono">
            Endpoint: ai.gateway.lovable.dev (OpenAI-compatible)
          </p>
        </div>

        <div className="flex items-center gap-2 pt-2">
          <Button
            size="sm"
            disabled={!dirty}
            onClick={() => {
              save(draft);
              toast.success("AI settings saved");
            }}
          >
            Save
          </Button>
          <Button
            size="sm"
            variant="ghost"
            disabled={!dirty}
            onClick={() => setDraft(settings)}
          >
            Discard
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              reset();
              toast.success("Reset to defaults");
            }}
            className="ml-auto"
          >
            Reset defaults
          </Button>
        </div>
      </section>

      {/* Test */}
      <section className="border border-border rounded-[3px] bg-panel p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div>
            <Label className="text-[13px] text-text-primary">
              Test connection
            </Label>
            <p className="text-[12px] text-text-muted mt-0.5">
              Sends a one-token "say hello" completion using the current
              draft model.
            </p>
          </div>
          <Button size="sm" onClick={onTest} disabled={testing}>
            {testing ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin mr-1.5" />
                Testing…
              </>
            ) : (
              "Run test"
            )}
          </Button>
        </div>
        {result && (
          <div
            className={`text-[12px] font-mono p-2 rounded-[3px] border flex items-start gap-2 ${
              result.ok
                ? "border-accent/40 bg-accent/5 text-text-primary"
                : "border-destructive/50 bg-destructive/5 text-destructive"
            }`}
          >
            {result.ok ? (
              <CheckCircle2 className="w-3.5 h-3.5 mt-0.5 text-accent shrink-0" />
            ) : (
              <AlertCircle className="w-3.5 h-3.5 mt-0.5 shrink-0" />
            )}
            <span className="break-words">{result.text}</span>
          </div>
        )}
      </section>
    </div>
  );
}

export default AiSettings;